---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  product_name: chef
  channel: current

platforms:
  - name: windows-2012R2

verifier:
  name: inspec

suites:
  - name: app
    run_list:
      - recipe[test::app]
  - name: config_property
    run_list:
      - recipe[test::config_property]
  - name: module
    run_list:
      - recipe[test::module]
  - name: pool
    run_list:
      - recipe[test::pool]
  - name: root
    run_list:
      - recipe[test::root]
  - name: section
    run_list:
      - recipe[test::section]
  - name: site
    run_list:
      - recipe[test::site]
  - name: vdir
    run_list:
      - recipe[test::vdir]
